### ISSUE TITLE
authorized keys passphrase

### ISSUE THREAD

**Issue by nicolaibaralmueller** [geekinutah/docker-ssh-jumphost#1]
Hi,

I found this trying to solve my issue:

[https://stackoverflow.com/questions/59422867/docker-container-as-ssh-tunnel-with-existing-public-key-and-skip-passphrase](url)

Now I also tried your image but I'm still prompted for passphrase. Do you know how to solve this?

**Comment by geekinutah** [comment]
I'm going to guess this has already been resolved. If not, feel free to re-open.
